[mgr]
prepend_keymap = [
    { on = [ "<C-S-i>" ], run = "plugin info-popup", desc = "Toggle file/directory information" }
]

[confirm]
prepend_keymap = [
    { on = [ "<C-S-i>" ], run = "close", desc = "Close file/directory information" }
]
