-- Generated by HyprMod

-- Environment
hl.env("XCURSOR_THEME", "ArcStarry-cursors")
hl.env("XCURSOR_SIZE", "24")

-- Settings
hl.config({
    general = {
        col = {
            active_border = {
                colors = {"rgba(a5c8ffff)", "rgba(99c1f1ff)"},
                angle = 90,
            },
        },
        gaps_in = 2,
        gaps_out = 7,
    },
    input = {
        kb_layout = "gb,br",
        kb_options = "grp:alt_shift_toggle,caps:escape_shifted_capslock",
        numlock_by_default = true,
    },
})

-- Monitors
hl.monitor({
    output = "DP-5",
    disabled = false,
    mode = "1920x1080@60.00Hz",
    position = "-1920x0",
    scale = 1,
    cm = "srgb",
})
hl.monitor({
    output = "eDP-1",
    disabled = false,
    mode = "1920x1080@60.05Hz",
    position = "0x0",
    scale = 1,
    cm = "srgb",
})
